# -*- coding: utf-8 -*-
path = 'frontend/src/pages/Dashboard.tsx'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

START_MARKER = '          {/* \u2500\u2500 Rel\u00f3gio de Mercado'
END_MARKER   = '          })()}'

start_idx = content.find(START_MARKER)
assert start_idx != -1, "Start marker not found"
end_idx = content.find(END_MARKER, start_idx)
assert end_idx != -1, "End marker not found"
end_idx += len(END_MARKER)

print(f"Replacing chars {start_idx}..{end_idx}")

NEW = (
    "          {/* \u2500\u2500 Rel\u00f3gio de Mercado \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500 */}\n"
    "          {(() => {\n"
    "            const tzOff = (tz: string): number => {\n"
    "              const utc = new Date(clockNow.toLocaleString('en-US', { timeZone: 'UTC' }));\n"
    "              const loc = new Date(clockNow.toLocaleString('en-US', { timeZone: tz }));\n"
    "              return Math.round((loc.getTime() - utc.getTime()) / 3600000);\n"
    "            };\n"
    "\n"
    "            const londonOff = tzOff('Europe/London');\n"
    "            const nyOff     = tzOff('America/New_York');\n"
    "            const sydneyOff = tzOff('Australia/Sydney');\n"
    "\n"
    "            const toBRT = (lh: number, off: number) => ((lh - off - 3) % 24 + 24) % 24;\n"
    "\n"
    "            const sydS = toBRT(8,  sydneyOff);\n"
    "            const sydE = toBRT(17, sydneyOff);\n"
    "            const tokS = 21;\n"
    "            const tokE = 6;\n"
    "            const lonS = toBRT(7,  londonOff);\n"
    "            const lonE = toBRT(16, londonOff);\n"
    "            const nyS  = toBRT(8,  nyOff);\n"
    "            const nyE  = toBRT(17, nyOff);\n"
    "            const ovS  = Math.max(lonS, nyS);\n"
    "            const ovE  = Math.min(lonE, nyE);\n"
    "\n"
    "            const h   = clockNow.getHours();\n"
    "            const min = clockNow.getMinutes();\n"
    "            const dow = clockNow.getDay();\n"
    "\n"
    "            const pad = (n: number) => String(n).padStart(2, '0');\n"
    "            const timeStr = `${pad(h)}:${pad(min)}`;\n"
    "\n"
    "            const isOpenRange = (s: number, e: number) =>\n"
    "              s < e ? h >= s && h < e : h >= s || h < e;\n"
    "\n"
    "            const forexOpen =\n"
    "              dow !== 6 &&\n"
    "              !(dow === 0 && h < sydS) &&\n"
    "              !(dow === 5 && h >= nyE);\n"
    "\n"
    "            const sessions = [\n"
    "              { name: 'Sydney',    emoji: '\U0001F998', start: sydS, end: sydE, color: '#22c55e',\n"
    "                desc: 'Asi\u00e1tica' },\n"
    "              { name: 'T\u00f3quio',    emoji: '\U0001F5FC', start: tokS, end: tokE, color: '#22c55e',\n"
    "                desc: 'Asi\u00e1tica' },\n"
    "              { name: 'Londres',   emoji: '\U0001F3A1', start: lonS, end: lonE, color: '#3b82f6',\n"
    "                desc: londonOff === 1 ? 'Europeia \u2022 BST' : 'Europeia \u2022 GMT' },\n"
    "              { name: 'Nova York', emoji: '\U0001F5FD', start: nyS,  end: nyE,  color: '#ef4444',\n"
    "                desc: nyOff === -4   ? 'Americana \u2022 EDT' : 'Americana \u2022 EST' },\n"
    "            ];\n"
    "\n"
    "            const overlapOpen = forexOpen && ovS < ovE && isOpenRange(ovS, ovE);\n"
    "\n"
    "            // Minutos at\u00e9 a pr\u00f3xima abertura de uma hora (BRT)\n"
    "            const minsTo = (startH: number) => {\n"
    "              const sm = startH * 60, nm = h * 60 + min;\n"
    "              return sm > nm ? sm - nm : 24 * 60 - nm + sm;\n"
    "            };\n"
    "            const fmt = (startH: number) => {\n"
    "              const m = minsTo(startH);\n"
    "              if (m < 60) return `em ${m}min`;\n"
    "              const hh = Math.floor(m / 60), mm = m % 60;\n"
    "              return mm > 0 ? `em ${hh}h${pad(mm)}` : `em ${hh}h`;\n"
    "            };\n"
    "            type Candidate = { key: string; startH: number; open: boolean };\n"
    "            const candidates: Candidate[] = [\n"
    "              ...sessions.map(s => ({ key: s.name, startH: s.start, open: forexOpen && isOpenRange(s.start, s.end) })),\n"
    "              { key: 'overlap', startH: ovS, open: overlapOpen },\n"
    "            ];\n"
    "            const closed = candidates.filter(c => !c.open);\n"
    "            const nextKey = closed.length > 0\n"
    "              ? closed.reduce((b, c) => minsTo(c.startH) < minsTo(b.startH) ? c : b).key\n"
    "              : null;\n"
    "\n"
    "            return (\n"
    "              <div className=\"panel market-clock-panel\">\n"
    "                <div className=\"panel-header\">\n"
    "                  <h4>\U0001F552 Hor\u00e1rio de mercado</h4>\n"
    "                  <span style={{ fontVariantNumeric: 'tabular-nums', fontSize: '15px', fontWeight: 700, opacity: 0.9 }}>\n"
    "                    {timeStr} BRT\u00a0\u00a0\n"
    "                    <span style={{ fontSize: '12px', fontWeight: 600, color: forexOpen ? 'var(--accent)' : '#94a3b8' }}>\n"
    "                      {forexOpen ? '\u25cf Forex aberto' : '\u25cf Forex fechado'}\n"
    "                    </span>\n"
    "                  </span>\n"
    "                </div>\n"
    "\n"
    "                <div className=\"market-sessions\">\n"
    "                  {sessions.map(s => {\n"
    "                    const open = forexOpen && isOpenRange(s.start, s.end);\n"
    "                    const isNext = !open && nextKey === s.name;\n"
    "                    return (\n"
    "                      <div key={s.name} className={`market-session ${open ? 'open' : 'closed'}${isNext ? ' next' : ''}`}>\n"
    "                        <div className=\"ms-header\">\n"
    "                          <span className=\"ms-flag\">{s.emoji}</span>\n"
    "                          <span className=\"ms-name\">{s.name}</span>\n"
    "                          <span className=\"ms-badge\" style={{ background: open ? s.color + '33' : isNext ? 'rgba(251,191,36,0.15)' : undefined, color: open ? s.color : isNext ? '#fbbf24' : undefined }}>\n"
    "                            {open ? 'aberto' : isNext ? 'pr\u00f3ximo' : 'fechado'}\n"
    "                          </span>\n"
    "                        </div>\n"
    "                        <div className=\"ms-hours\">{s.start}h \u2192 {s.end}h</div>\n"
    "                        <div className=\"ms-desc\">{open ? s.desc : isNext ? fmt(s.start) : s.desc}</div>\n"
    "                      </div>\n"
    "                    );\n"
    "                  })}\n"
    "\n"
    "                  <div className={`market-session overlap ${overlapOpen ? 'open' : 'closed'}${nextKey === 'overlap' ? ' next' : ''}`}>\n"
    "                    <div className=\"ms-header\">\n"
    "                      <span className=\"ms-flag\">\U0001F525</span>\n"
    "                      <span className=\"ms-name\">Londres + NY</span>\n"
    "                      <span className=\"ms-badge\" style={{ background: overlapOpen ? '#f59e0b33' : nextKey === 'overlap' ? 'rgba(251,191,36,0.15)' : undefined, color: overlapOpen ? '#f59e0b' : nextKey === 'overlap' ? '#fbbf24' : undefined }}>\n"
    "                        {overlapOpen ? 'AGORA' : nextKey === 'overlap' ? 'pr\u00f3ximo' : 'aguardando'}\n"
    "                      </span>\n"
    "                    </div>\n"
    "                    <div className=\"ms-hours\">{ovS}h \u2192 {ovE}h</div>\n"
    "                    <div className=\"ms-desc\">{overlapOpen ? 'Melhor hor\u00e1rio \u2022 +50% do volume' : nextKey === 'overlap' ? fmt(ovS) : 'Melhor hor\u00e1rio \u2022 +50% do volume'}</div>\n"
    "                  </div>\n"
    "                </div>\n"
    "              </div>\n"
    "            );\n"
    "          })()}"
)

content = content[:start_idx] + NEW + content[end_idx:]

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Done! Next-to-open indicator added. Size: {len(content)} chars")
